version: "3.9"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyterlab
    image: a3_car_jupyter:latest
    ports:
      - "8888:8888"
    volumes:
      - ./code:/root/code
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow.ml.brain.cs.ait.ac.th/"
      MLFLOW_TRACKING_USERNAME: "admin"
      MLFLOW_TRACKING_PASSWORD: "password"
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --no-browser
    networks:
      - car-network

  dash:
    build:
      context: .
      dockerfile: Dockerfile
    image: a3-dash-car:latest
    ports:
      - "8050:8050"
    volumes:
      - ./code:/root/code
    command: ["python3", "/root/code/app.py"]
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow.ml.brain.cs.ait.ac.th/"
      MLFLOW_TRACKING_USERNAME: "admin"
      MLFLOW_TRACKING_PASSWORD: "password"
      PYTHONPATH: "/root/code"
    networks:
      - car-network

networks:
  car-network:
    driver: bridge
