name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
      MLFLOW_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      RUN_ID: ${{ secrets.RUN_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          export PYTHONPATH=$(pwd)/code
          python -m pytest tests/ -v
