name: Run Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: mlflow
          POSTGRES_PASSWORD: mlflow
          POSTGRES_DB: mlflow
        ports:
          - 5433:5432

      mlflow:
        image: ghcr.io/mlflow/mlflow:latest
        ports:
          - 5001:5001
        volumes:
          - /tmp/mlruns:/mlruns
        options: >-
          --health-cmd="curl --fail http://localhost:5001/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        command: >
          mlflow server
          --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
          --default-artifact-root /mlruns
          --host 0.0.0.0
          --port 5001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          MLFLOW_TRACKING_URI: http://mlflow:5001
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/
